import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
// import Image from 'next/image'
import styles from "./Home.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Emma Stone-Johnson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Header />
        <ul>
          <li>
            <Link href="/paintings">Paintings</Link>
          </li>
          <li>
            <Link href="/contact">Contact</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
          {/* <li>
            <Link href="/cv">CV</Link>
          </li> */}
          <li>
            <Link href="/interviews">Interviews</Link>
          </li>
        </ul>
      </div>
    </>
  );
};

export default Home;
